print("doctor> Hallå!")
print("doctor> Vad är ditt förnamn?")
x = input("jag> Mitt förnamn är ")
print("doctor> Vad är ditt efternamn?")
y = input("jag> Mitt efternamn är ")
print("doctor> Trevlig att träffas " + x + " " + y)